package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/wayofthepie/task-store/pkg/model"

// EventService is an autogenerated mock type for the EventService type
type EventService struct {
	mock.Mock
}

// PublishWork provides a mock function with given fields: spec
func (_m *EventService) PublishWork(spec *model.TaskSpec) error {
	ret := _m.Called(spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.TaskSpec) error); ok {
		r0 = rf(spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
