package mocks

import "github.com/stretchr/testify/mock"
import (
	"github.com/NeowayLabs/wabbit"
	"github.com/execd/task-store/pkg/model"
)

// Rabbit is an autogenerated mock type for the Rabbit type
type Rabbit struct {
	mock.Mock
}

// GetTaskStatusQueueChan provides a mock function with given fields:
func (_m *Rabbit) GetTaskStatusQueueChan() <-chan wabbit.Delivery {
	ret := _m.Called()

	var r0 <-chan wabbit.Delivery
	if rf, ok := ret.Get(0).(func() <-chan wabbit.Delivery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan wabbit.Delivery)
		}
	}

	return r0
}

// PublishWork provides a mock function with given fields: task
func (_m *Rabbit) PublishWork(task *model.Spec) error {
	ret := _m.Called(task)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Spec) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
